security:
    encoders:
        Tienvx\Bundle\MbtApiBundle\Entity\User:
            algorithm: bcrypt

    providers:
        user_db_provider:
            entity:
                class: Tienvx\Bundle\MbtApiBundle\Entity\User
                property: username

    firewalls:

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        register:
            pattern:  ^/api/register
            stateless: true
            anonymous: true

        model_image:
            pattern:  ^/api/models/.*/image
            security: false

        api:
            pattern:   ^/api/
            stateless: true
            user_checker: Tienvx\Bundle\MbtApiBundle\Security\UserChecker
            guard:
                authenticators:
                - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
    - { path: ^/api/login,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/,         roles: IS_AUTHENTICATED_FULLY }
