version: '3'
networks:
    selenoid:
        external:
            name: selenoid
services:
    db:
        image: jbergstroem/mariadb-alpine
        networks:
            selenoid: null
        environment:
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_ROOT_PASSWORD: root
    hub:
        image: "selenoid/hub"
        networks:
            selenoid: null
        volumes:
            - "$PWD/selenoid/config/:/etc/selenoid/:ro"
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "$PWD/selenoid/video/:/opt/selenoid/video"
            - "$PWD/selenoid/logs/:/opt/selenoid/logs"
        environment:
            - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/selenoid/video/
        command: ["-conf", "/etc/selenoid/browsers.json", "-limit", "4", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "selenoid"]
    selenoid-ui:
        image: "aerokube/selenoid-ui"
        networks:
            selenoid: null
        ports:
            - "85:8080"
        command: ["--selenoid-uri", "http://hub:4444"]
    minio:
        image:   'minio/minio'
        networks:
            selenoid: null
        ports:
            - 84:9000
        environment:
            # https://docs.minio.io/docs/minio-server-configuration-guide
            MINIO_ACCESS_KEY: "$AWS_S3_KEY"
            MINIO_SECRET_KEY: "$AWS_S3_SECRET"
            MINIO_REGION: "$AWS_S3_REGION"
        entrypoint: sh
        command: -c 'mkdir -p /data/mbt && minio server --address :9000 /data'
    app:
        image: 'tienvx/mbt-example-app'
        networks:
            selenoid:
                aliases:
                    - example.com
        ports:
            - 81:80
        depends_on:
            - db
    api:
        build:
            context: ..
            dockerfile: docker/Dockerfile.api
        networks:
            selenoid: null
        ports:
            - 82:80
        depends_on:
            - db
            - minio
        env_file:
            - .env
        deploy:
            replicas: 1
    worker:
        build:
            context: ..
            dockerfile: docker/Dockerfile.worker
        networks:
            selenoid: null
        depends_on:
            - db
            - minio
        env_file:
            - .env
        deploy:
            replicas: 4
        command: ["wait-for", "db:3306", "--timeout=99", "--", "php", "/usr/local/src/app/bin/console", "messenger:consume", "async"]
    admin:
        image: "tienvx/mbt-admin:v1.13.0"
        networks:
            selenoid: null
        ports:
            - 80:80
        depends_on:
            - api
        environment:
            API_URL: 'http://localhost:82'
